###### Database Properties  ###########################################
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: lol1409916
    url: jdbc:postgresql://localhost:5433/reddit
    username: postgres
  jpa:
    hibernate:
      #      create-drop; when application is running and stops - it resets and drops everything from registration1 data server
      ddl-auto: create-drop
    properties:
      hibernate:
############# Mail Properties <MailTrap> ###########################################

